import { raleway, dela } from "@/utils";
import "../styles/globals.css";
import { Footer, Header } from "@/components";

export const metadata = {
   title: "Homero Bracamonte",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={`${dela.variable} ${raleway.variable} overflow-x-hidden `}>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
